#!/bin/sh

# sspm 0 - shell script package manager
# Copyright (c) 2018, Maksim Pinigin

function package_check {
	wget -q --spider $REPO/index/$1
	if [ $? = 0 ]; then
		if [ $2 = 1 ]; then
			echo "Package $1 exists."
			DEPS=$(wget -q -O - $REPO/dependencies/$1)
			echo "Dependencies: $DEPS"
			return 0
		else
			return 0
		fi
	else
		if [ $2 = 1 ]; then
			echo "Package $1 is not exists."
			return 1
		else
			return 1
		fi
	fi
}

if [ -z $1 ]; then
	echo "Usage: $0 ACTION PARAMS..."
	echo ""
	echo "Actions list:"
	echo "  check - check for package existence"
	echo ""
	echo "Send bug reports to https://github.com/estintax/sspm"
else
	REPO=$(cat /etc/sspm/repository)
	if [ $? = 1 ]; then
		echo "Please, specify repository in /etc/sspm/repository"
		exit 2
	fi
	if [ $1 = "check" ]; then
		if [ -z $2 ]; then
			echo "Usage: $0 $1 PACKAGE"
		else
			package_check $2 1
		fi
	fi
fi
